# write github actions for python test

name: Upload Python Package

on: [push, pull_request]

env:
  PYTHON_VERSION: 3.10
  MARKETWATCH_USERNAME: ${{ variables.MARKETWATCH_USERNAME }}
  MARKETWATCH_PASSWORD: ${{ secrets.MARKETWATCH_PASSWORD }}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: PYTHON_VERSION
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest


