# write github actions for python test

name: Upload Python Package

on: [push, pull_request]

env:
  PYTHON_VERSION: 3.10
  MARKETWATCH_USERNAME: ${{ secrets.MARKETWATCH_USERNAME }}
  MARKETWATCH_PASSWORD: ${{ secrets.MARKETWATCH_PASSWORD }}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: PYTHON_VERSION
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Export Environment Variables
        run: |
          echo "MARKETWATCH_USERNAME=${MARKETWATCH_USERNAME}" >> $GITHUB_ENV
          echo "MARKETWATCH_PASSWORD=${MARKETWATCH_PASSWORD}" >> $GITHUB_ENV
          export MARKETWATCH_USERNAME
          export MARKETWATCH_PASSWORD
      - name: Test with pytest
        run: |
          poetry run pytest
      - name: Build package
        run: poetry build
        

